name: Check Website Every 10 Minutes

# This workflow checks a website every 10 minutes and runs a Python script to process data.
# It also commits signatures.tsv to the repo


on:
  schedule:
    - cron: '*/10 * * * *'  # Toutes les 10 minutes (UTC)
  workflow_dispatch:  # Permet de le lancer manuellement aussi


permissions:  
  contents: write  # Nécessaire pour pouvoir pousser les modifications dans le dépôt
  identities: read  # Nécessaire pour lire les entités d'identification (comme le token GITHUB_TOKEN)
  



jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run loi_duplomb.py
        run: python loi_duplomb.py signatures.tsv

      - name: Commit updated signatures.tsv if changed
        run: |
          set -x
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add signatures.tsv
          git diff --cached --quiet || git commit -m "Update signatures.tsv"
          # Push avec token dans l'URL
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/francois-lecoquierre/duplomb_dans_l_aile.git HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            signatures.tsv



